#!/bin/bash

#Add users
echo "Adding users"
sudo useradd -m -p 123456 -s /bin/bash dzengiz > /dev/null
sudo useradd -m -p 123456 -s /bin/bash patrick > /dev/null
sudo useradd -m -p 123456 -s /bin/bash solaiman > /dev/null
sudo useradd -m -p 123456 -s /bin/bash mariette > /dev/null
sudo useradd -m -p 123456 -s /bin/bash koen > /dev/null
sudo useradd -m -p 123456 -s /bin/bash kadrie > /dev/null
sudo useradd -m -p 123456 -s /bin/bash niels > /dev/null
sudo useradd -m -p 123456 -s /bin/bash jimmy > /dev/null
sudo useradd -m -p 123456 -s /bin/bash johan > /dev/null
sudo useradd -m -p 123456 -s /bin/bash michel > /dev/null
sudo useradd -m -p 123456 -s /bin/bash mikail > /dev/null
sudo useradd -m -p 123456 -s /bin/bash peter > /dev/null
sudo useradd -m -p 123456 -s /bin/bash obaidullah > /dev/null
sudo useradd -m -p 123456 -s /bin/bash caroline > /dev/null

#Creating samba password
echo "Samba password creation"
echo -ne "123456\n123456" | smbpasswd -a dzengiz > /dev/null
echo -ne "123456\n123456" | smbpasswd -a patrick > /dev/null
echo -ne "123456\n123456" | smbpasswd -a solaiman > /dev/null
echo -ne "123456\n123456" | smbpasswd -a mariette > /dev/null
echo -ne "123456\n123456" | smbpasswd -a koen > /dev/null
echo -ne "123456\n123456" | smbpasswd -a kadrie > /dev/null
echo -ne "123456\n123456" | smbpasswd -a niels > /dev/null
echo -ne "123456\n123456" | smbpasswd -a jimmy > /dev/null
echo -ne "123456\n123456" | smbpasswd -a johan > /dev/null
echo -ne "123456\n123456" | smbpasswd -a michel > /dev/null
echo -ne "123456\n123456" | smbpasswd -a mikail > /dev/null
echo -ne "123456\n123456" | smbpasswd -a peter > /dev/null
echo -ne "123456\n123456" | smbpasswd -a obaidullah > /dev/null
echo -ne "123456\n123456" | smbpasswd -a caroline > /dev/null

# Creating users groups
echo "Creating users groups"
sudo groupadd public > /dev/null

sudo groupadd R_DTP > /dev/null
sudo groupadd R_training > /dev/null
sudo groupadd R_projecten > /dev/null
sudo groupadd R_locaties > /dev/null
sudo groupadd R_media > /dev/null
sudo groupadd R_training > /dev/null
sudo groupadd R_intern > /dev/null
sudo groupadd R_varia > /dev/null

sudo groupadd RW_DTP > /dev/null
sudo groupadd RW_training > /dev/null
sudo groupadd RW_projecten > /dev/null
sudo groupadd RW_refurb > /dev/null
sudo groupadd RW_digiwie > /dev/null
sudo groupadd RW_geocache > /dev/null
sudo groupadd RW_locaties > /dev/null
sudo groupadd RW_media > /dev/null
sudo groupadd RW_training > /dev/null
sudo groupadd RW_intern > /dev/null
sudo groupadd RW_varia > /dev/null

sudo groupadd admin > /dev/null

#Adding users to Admin group
echo "Adding users to Admin group"
usermod obaidullah -aG admin > /dev/null
usermod dzengiz -aG admin > /dev/null
usermod patrick -aG admin > /dev/null

#Adding users to public group
echo "Adding users to public group"
usermod dzengiz -aG public > /dev/null
usermod patrick -aG public > /dev/null
usermod solaiman -aG public > /dev/null
usermod mariette -aG public > /dev/null
usermod koen -aG public > /dev/null
usermod kadrie -aG public > /dev/null
usermod niels -aG public > /dev/null
usermod jimmy -aG public > /dev/null
usermod johan -aG public > /dev/null
usermod michel -aG public > /dev/null
usermod mikail -aG public > /dev/null
usermod peter -aG public > /dev/null
usermod obaidullah -aG public > /dev/null
usermod caroline -aG public > /dev/null

#Adding users to R_training group
echo "Adding users to R_training group"
usermod dzengiz -aG R_training > /dev/null
usermod patrick -aG R_training > /dev/null
usermod solaiman -aG R_training > /dev/null
usermod mariette -aG R_training > /dev/null
usermod koen -aG R_training > /dev/null
usermod kadrie -aG R_training > /dev/null
usermod niels -aG R_training > /dev/null
usermod jimmy -aG R_training > /dev/null
usermod johan -aG R_training > /dev/null
usermod michel -aG R_training > /dev/null
usermod mikail -aG R_training > /dev/null
usermod peter -aG R_training > /dev/null
usermod obaidullah -aG R_training > /dev/null
usermod caroline -aG R_training > /dev/null

#Adding users to RW_training group
echo "Adding users to RW_training group"
usermod dzengiz -aG RW_training > /dev/null
usermod patrick -aG RW_training > /dev/null
usermod jimmy -aG RW_training > /dev/null
usermod michel -aG RW_training > /dev/null

#Adding users to R_DTP group
echo "Adding users to R_DTP group"
usermod dzengiz -aG R_DTP > /dev/null
usermod solaiman -aG R_DTP > /dev/null
usermod mariette -aG R_DTP > /dev/null
usermod koen -aG R_DTP > /dev/null
usermod kadrie -aG R_DTP > /dev/null
usermod niels -aG R_DTP > /dev/null
usermod jimmy -aG R_DTP > /dev/null
usermod johan -aG R_DTP > /dev/null
usermod michel -aG R_DTP > /dev/null
usermod mikail -aG R_DTP > /dev/null
usermod peter -aG R_DTP > /dev/null
usermod obaidullah -aG R_DTP > /dev/null

#Adding users to RW_DTP group
echo "Adding users to RW_DTP group"
usermod patrick -aG RW_DTP > /dev/null

#Adding users to R_projecten group
echo "Adding users to R_projecten group"
usermod dzengiz -aG R_projecten > /dev/null
usermod solaiman -aG R_projecten > /dev/null
usermod mariette -aG R_projecten > /dev/null
usermod koen -aG R_projecten > /dev/null
usermod kadrie -aG R_projecten > /dev/null
usermod niels -aG R_projecten > /dev/null
usermod jimmy -aG R_projecten > /dev/null
usermod johan -aG R_projecten > /dev/null
usermod michel -aG R_projecten > /dev/null
usermod mikail -aG R_projecten > /dev/null
usermod peter -aG R_projecten > /dev/null
usermod obaidullah -aG R_projecten > /dev/null

#Adding users to RW_projecten group
echo "Adding users to RW_projecten group"
usermod patrick -aG RW_projecten > /dev/null

#Adding users to RW_refurb group
echo "Adding users to RW_refurb group"
usermod patrick -aG RW_refurb > /dev/null
usermod dzengiz -aG RW_refurb > /dev/null
usermod solaiman -aG RW_refurb > /dev/null
usermod mariette -aG RW_refurb > /dev/null
usermod koen -aG RW_refurb > /dev/null
usermod kadrie -aG RW_refurb > /dev/null
usermod niels -aG RW_refurb > /dev/null
usermod jimmy -aG RW_refurb > /dev/null
usermod johan -aG RW_refurb > /dev/null
usermod michel -aG RW_refurb > /dev/null
usermod mikail -aG RW_refurb > /dev/null
usermod peter -aG RW_refurb > /dev/null
usermod obaidullah -aG RW_refurb > /dev/null

#Adding users to RW_digiwie group
echo "Adding users to RW_digiwie group"
usermod patrick -aG RW_digiwie > /dev/null
usermod dzengiz -aG RW_digiwie > /dev/null
usermod niels -aG RW_digiwie  > /dev/null
usermod obaidullah -aG RW_digiwie > /dev/null

#Adding users to RW_geocache group
echo "Adding users to RW_digiwie group"
usermod patrick -aG RW_digiwie > /dev/null
usermod johan -aG RW_digiwie > /dev/null

#Adding users to R_locaties group
echo "Adding users to R_locaties group"
usermod patrick -aG R_locaties > /dev/null
usermod dzengiz -aG R_locaties > /dev/null
usermod solaiman -aG R_locaties > /dev/null
usermod mariette -aG R_locaties > /dev/null
usermod koen -aG R_locaties > /dev/null
usermod kadrie -aG R_locaties > /dev/null
usermod niels -aG R_locaties > /dev/null
usermod jimmy -aG R_locaties > /dev/null
usermod johan -aG R_locaties > /dev/null
usermod michel -aG R_locaties > /dev/null
usermod mikail -aG R_locaties > /dev/null
usermod peter -aG R_locaties > /dev/null
usermod obaidullah -aG R_locaties > /dev/null

#Adding users to RW_locaties group
echo "Adding users to RW_locaties group"
usermod patrick -aG RW_locaties > /dev/null

#Adding users to R_intern group
echo "Adding users to R_intern group"
usermod patrick -aG R_intern > /dev/null
usermod dzengiz -aG R_intern > /dev/null
usermod solaiman -aG R_intern > /dev/null
usermod mariette -aG R_intern > /dev/null
usermod koen -aG R_intern > /dev/null
usermod kadrie -aG R_intern > /dev/null
usermod niels -aG R_intern > /dev/null
usermod jimmy -aG R_intern > /dev/null
usermod johan -aG R_intern > /dev/null
usermod michel -aG R_intern > /dev/null
usermod mikail -aG R_intern > /dev/null
usermod peter -aG R_intern > /dev/null
usermod obaidullah -aG R_intern > /dev/null

#Adding users to RW_intern group
echo "Adding users to RW_intern group"
usermod patrick -aG RW_intern > /dev/null


#creation of folders
echo "Creating folder structure"
sudo mkdir /srv/shares/
sudo mkdir /srv/shares/DTP/
sudo mkdir /srv/shares/DTP/public/

sudo mkdir /srv/shares/DTP/projecten/
sudo mkdir /srv/shares/DTP/projecten/refurb/
sudo mkdir /srv/shares/DTP/projecten/digiwie/
sudo mkdir /srv/shares/DTP/projecten/geocache/

sudo mkdir /srv/shares/DTP/locaties/
sudo mkdir /srv/shares/DTP/locaties/vlaamsekaai/
sudo mkdir /srv/shares/DTP/locaties/brugsesteenweg/
sudo mkdir /srv/shares/DTP/locaties/uco/
sudo mkdir /srv/shares/DTP/locaties/ingent/
sudo mkdir /srv/shares/DTP/locaties/pannestraat/
sudo mkdir /srv/shares/DTP/locaties/oude_houtlei/
sudo mkdir /srv/shares/DTP/locaties/de_krook/

sudo mkdir /srv/shares/DTP/media/
sudo mkdir /srv/shares/DTP/training/
sudo mkdir /srv/shares/DTP/intern/
sudo mkdir /srv/shares/DTP/varia/


#Permission and ownership
echo "Setting permission and ownership"
sudo chmod -R 0770 /srv/shares/DTP > /dev/null
sudo chown -R digiadmin:RW_DTP /srv/shares/DTP > /dev/null
sudo chown -R root:RW_DTP /srv/shares/DTP > /dev/null


#Creation of smb.conf
echo "Creating smb.conf file"
echo "... removing old samba config"
sudo rm -rf smb.conf

echo "... setting up new samba config"
cat > /etc/samba/smb.conf << EOF
[global]
        workgroup = SAMBA
        security = user

        passdb backend = tdbsam
        netbios name = files

        printing = cups
        printcap name = cups
        load printers = yes
        cups options = raw

[homes]
        comment = Home Directories
        browseable = Yes
        writable = Yes
        valid users = %S

[public]
        comment = Secure File Server Share
        path =  /srv/shares/public
        valid users = @public
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = public

[training]
        comment = Secure File Server Share
        path =  /srv/shares/training
        valid users = @R_training
        write list = @admin, @RW_training
        guest ok = no
        writable = no
        browsable = yes

        force directory mode = 770
        force create mode = 770

        force group = RW_training

[DTP]
        comment = Secure File Server Share
        path =  /srv/shares/DTP
        valid users = @R_DTP
        write list = @admin, @RW_DTP
        guest ok = no
        writable = no
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_DTP

[projecten]
        comment = Secure File Server Share
        path =  /srv/shares/projecten
        valid users = @R_projecten
        write list = @RW_projecten
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_projecten

[refurb]
        comment = Secure File Server Share
        path =  /srv/shares/projecten/refurb
        valid users = @RW_refurb
        write list = @RW_refurb
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_refurb

[digiwie]
        comment = Secure File Server Share
        path =  /srv/shares/projecten/digiwie
        valid users = @R_projecten
        write list = @RW_digiwie
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_digiwie

[geocache]
        comment = Secure File Server Share
        path =  /srv/shares/projecten/geocache
        valid users = @R_projecten
        write list = @RW_geocache
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_geocache

[locaties]
        comment = Secure File Server Share
        path =  /srv/shares/locaties
        valid users = @R_locaties
        write list = @RW_locaties
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_locaties

[training]
        comment = Secure File Server Share
        path =  /srv/shares/training
        valid users = @R_training
        write list = @RW_training
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_training

[intern]
        comment = Secure File Server Share
        path =  /srv/shares/intern
        valid users = @R_intern
        write list = @RW_intern
        guest ok = no
        writable = yes
        browsable = yes

        force directory mode = 770
        force create mode = 770
        force group = RW_intern
EOF

#Stop and start samba
echo "Stop and start samba"
sudo service smbd restart > /dev/null

echo "#################################"
echo "#### User shares are now set ####"
echo "#################################"
